### ISSUE TITLE
Error in GUI! (..../#tab-instances/config/system.adapter.jsonconfig-demo.0)

### ISSUE THREAD

**Issue by smarthausleben** [mcm4iob/ioBroker.jsonconfig-demo#1]
occurred at opening of  **_tab_3_**

instrument.ts:124 TypeError: G is not a function
    at KeyboardDateInput.js:32:10
    at Fi (react-dom.production.min.js:167:137)
    at Ps (react-dom.production.min.js:193:57)
    at oa (react-dom.production.min.js:294:275)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)

**Comment by mcm1957** [comment]
An admin crash shoul eprimary reported at ioBroker.admin repo.
But I will try to investigate enayway.

Please add the stanadars infos.
- admin version used
- js-controller version used
- node version in use
- system type 

Please indicate too:
- language selected
aned ensure that you are NOT using an automatic translation service at your browser

With tab_3 you refer to tab labelled pickers? 

Currently the problem cannot nbe reproduced.

**Comment by smarthausleben** [comment]
I just installed your adapter in an ioBroker test environment running in a buanet/iobroker (v8.0.0) docker container on my synology.

The crash occurred at opening of the third tab. But I have no idea what name it has. 

Since the crash of the adapter it is not running anymore. Deinstallation and reinstallation in ioBroker didn’t fix the problem. Restart of the docker container didn’t fix it as well. But since it is running in a docker container I will not investigate further more. Analyzing your jsonConfig.json5 file is a big help as well.

System information.
Docker image: buanet/iobroker 8.0.0
Admin: 6.3.5 
Node: 18.16.0
js-controller: 4.0.24
language: German (no automatic translation)

**Comment by smarthausleben** [comment]
I did some more digging 😊 Maybe this helps a bit.

I just figured out that cleaning the browser cache for this site did fixed the crash and I could open the configuration again.

_**PICKERS**_ tab leads to crash in all browsers my (firefox/crome/opera/brave) and cleaning cache for the ioBroker site fixes the issue in all browsers. The other tabs worked fine.

**Comment by mcm1957** [comment]
Thanks for the additional info.
I'll try to reproduce

**Comment by mcm1957** [comment]
The issue seems to be caused by admin.
Please upgrade to admin 6.4.4 (latest release). 
At least for me the problem is reproduceable with admin 6.3.x but vanished with 6.4.4

Thnaks for reporting the issue

**Comment by smarthausleben** [comment]
For Admin `6.4.4` I had to switch to beta repositories first.
Yep, I can confirm that admin `6.4.4` did fix the problem.
Thanks
