### ISSUE TITLE
width nit working correctly in tables 

### ISSUE THREAD

**Issue by hombach** [mcm4iob/ioBroker.jsonconfig-demo#21]
looks like width isn't really working in tables. Same in my adapter. I tried "50%"; "50% "; 300; "300px"; "300px " .... everything not changing anything

BTW: Great idea to have this type of demo adapter!!

**Comment by mcm1957** [comment]
Well - there WAS a issue, but it's closed.
https://github.com/ioBroker/ioBroker.admin/issues/1333

Anyway - this is no isse for the demo adapter but for jsonConfig / admin itself.

Please open a issue here:
https://github.com/ioBroker/ioBroker.admin/issues/new/choose

Note: please add 'jsonConfig' to topic to make it easier to search fir.
